### ISSUE TITLE
Change .jsnb format to resemble .ipynb more.

### ISSUE THREAD

**Issue by Pokute** [joaomoreno/vscode-javascript-notebooks#11]
[Here's an example .ipynb -file](https://cantera.org/examples/jupyter/thermo/flame_temperature.ipynb)

The `.ipynb` -files have a good structure for diffing etc by having multiple lines inside the JSON. The source for an code block is an array of lines as strings.

This is example `.jsnb` -file: `[{"kind":1,"language":"markdown","value":"**JavaScript support**"},{"kind":2,"language":"javascript","value":"1 + 2 + 3"},{"kind":1,"language":"markdown","value":"**Function definition support**"},{"kind":2,"language":"javascript","value":"function add(x, y) {\r\n  return x + y;\r\n}"},{"kind":2,"language":"javascript","value":"add(1000, 337)"}]`.

`.jsnb` file doesn't have any linebreaks. Additionally source is a single string with line breaks done with `\r\n`. This means even a single character change in code or markdown will result in really unreadable diff.

Changing the format will obviously risk breaking existing notebooks, so this is better done sooner than later.

**Comment by joaomoreno** [comment]
It's a good point.

But diffing notebooks using their text formats also feels wrong. VS Code has native notebook diffing support, which can be used despite any underlying data format:

![image](https://user-images.githubusercontent.com/22350/147819105-bbd639c6-c14b-4357-bb8c-5c318e40d099.png)

I'd actually rather change to a more compact binary format rather than to a readable textual format.

**Comment by Pokute** [comment]
Ok. I put priority in normal git's diff and diff of tools like github, which are very difficult to read without line breaks, but priorities differ.
